# Generated by Django 4.2.2 on 2023-06-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfoMoodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=25, verbose_name='Телефон')),
                ('e_mail', models.CharField(max_length=20, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'Инфо',
                'verbose_name_plural': 'Инфо',
            },
        ),
        migrations.CreateModel(
            name='QualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_name', models.CharField(max_length=200, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='SpecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=200, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='GraduateInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='uploads/graduates/foto/', verbose_name='Фото')),
                ('year_of_admission', models.DateField(verbose_name='Дата поступления')),
                ('year_of_issue', models.DateField(verbose_name='Дата выпуска')),
                ('diplom', models.ImageField(blank=True, upload_to='uploads/graduates/diplom/', verbose_name='Диплом')),
                ('pril_ru', models.ImageField(blank=True, upload_to='uploads/graduates/prilru/', verbose_name='Приложение РУ')),
                ('pril_kaz', models.ImageField(blank=True, upload_to='uploads/graduates/prilkaz/', verbose_name='Приложение КАЗ')),
                ('skill_pass', models.ImageField(blank=True, upload_to='uploads/graduates/skills_pass/', verbose_name='Skills-паспорт')),
                ('ytb_url', models.CharField(blank=True, max_length=500, verbose_name='Видео')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('qual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.qualmodel', verbose_name='Квалификация')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.specmodel', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
            },
        ),
    ]
